### ISSUE TITLE
Theme disables all uploads.

### ISSUE THREAD

**Issue by scramblr** [ZacharyTalis/peertube-theme-pacerip#1]
After installing this theme, peertube no longer allows uploads of any kind. The buttons normally marked "Select the file to upload" are replaced with "Uploads are disabled".

**Comment by ZacharyTalis** [comment]
@scramblr Yes, that's intended behavior (PaceRIP is a streaming-only instance). You can override these stylings to revert the change:

`assets/style.css - Line 303`
```css
.first-step-block .button-file.form-control {
    visibility: hidden !important;
    position: relative !important;
}

.first-step-block .button-file.form-control:after {
    visibility: visible !important;
    position: absolute !important;
    top: 0 !important;
    left: 0 !important;
    content: "File upload disabled." !important;
    color: var(--actionButtonColor) !important;
}

.first-step-block ngb-tooltip-window {
    visibility: hidden !important;
}
```

Let me know if you've got any questions/issues <3
